# Generated by Django 4.0.1 on 2022-01-16 07:06

import CRUD.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=50)),
                ('description', models.CharField(help_text='Description', max_length=100)),
                ('symbol', models.CharField(help_text='Symbol', max_length=10)),
                ('market_values', models.TextField(default=CRUD.models.random_list)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
